### ISSUE TITLE
'db:init' errored after 298 μs

### ISSUE THREAD

**Issue by Chrisedmo** [timkelty/shipit-db#10]
Im getting the following errors when trying to pull my production DB:

```
Running 'db:init' task...
'db:init' errored after 298 μs
TypeError: Arguments to path.join must be strings
    at Object.module.exports [as join] (/usr/local/lib/node_modules/shipit-db/node_modules/path2/posix/join.js:10:10)
    at Shipit.task (/usr/local/lib/node_modules/shipit-db/tasks/db/init.js:16:31)
    at module.exports (/usr/local/lib/node_modules/shipit-cli/node_modules/orchestrator/lib/runTask.js:34:7)
    at Shipit.Orchestrator._runTask (/usr/local/lib/node_modules/shipit-cli/node_modules/orchestrator/index.js:273:3)
    at Shipit.Orchestrator._runStep (/usr/local/lib/node_modules/shipit-cli/node_modules/orchestrator/index.js:214:10)
    at Shipit.Orchestrator.start (/usr/local/lib/node_modules/shipit-cli/node_modules/orchestrator/index.js:134:8)
    at initShipit (/usr/local/lib/node_modules/shipit-cli/bin/shipit:81:10)
    at Liftoff.invoke (/usr/local/lib/node_modules/shipit-cli/bin/shipit:55:5)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/shipit-cli/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/shipit-cli/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/shipit-cli/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/shipit-cli/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/shipit-cli/node_modules/v8flags/index.js:108:14
    at /usr/local/lib/node_modules/shipit-cli/node_modules/v8flags/index.js:36:12
    at /usr/local/lib/node_modules/shipit-cli/node_modules/v8flags/index.js:47:7
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
    at node.js:999:3
Arguments to path.join must be strings
```

**Comment by Chrisedmo** [comment]
Hi @timkelty Did you have any joy replicating this?

**Comment by timkelty** [comment]
Are you running this via the `shipit` cli, or Grunt, Gulp, etc?

**Comment by Chrisedmo** [comment]
Hi @timkelty I was running it via the shipit-cli:
`shipit production db:pull`

**Comment by timkelty** [comment]
Can you post your shipit config, or the relevant parts of it?

**Comment by Chrisedmo** [comment]
Here you go…

I've changed details.

```
module.exports = function (shipit) {
  require('shipit-db')(shipit);

  shipit.initConfig({
    default: {
      db: {
        local: {
          host     : 'localhost',
          adapter  : 'mysql',
          username : 'root',
          password : 'root',
          socket   : '/Applications/MAMP/tmp/mysql/mysql.sock',
          database : 'database_name',
        },
      }
    },
    production: {
      servers: 'blahblah@website.com',
      db: {
        remote: {
          host     : '178.62.111.XXX',
          adapter  : 'mysql',
          username : 'username',
          password : 'password',
          database : 'database',
        }
      }
    }
  });
};

```

**Comment by timkelty** [comment]
Thanks, I'll dig into this.

**Comment by chrisrowe** [comment]
+1 on this

**Comment by Chrisedmo** [comment]
@chrisrowe did you try and pull first, or did you push first? I was trying to pull.

**Comment by travco** [comment]
Traced this back on the commit you were using. Error is on this line:
`shipit.currentPath = path.join(shipit.config.deployTo, 'current');`

Actually a shipitfile error. The way this set of tasks is set up you need to have deployTo set for whatever environment your using. eg:

``` js
shipit.initConfig({
    default: {
      deployTo: '/home/travco/FOO/shipit-db',
      workspace: '/home/travco/FOO/shipit-db',
      warnTasks: ['db:dumpfetch'],
      db: {
        ignoreTables: ['some_table'],
        local: {
          host     : 'localhost',
          adapter  : 'mysql',
          username : 'root',
          password : 'waffles',
          socket   : '/var/run/mysqld/mysqld.sock',
          database : 'test2',
        },
      }
    },
    staging: {
      servers: 'root@162.243.32.89',
      db: {
        remote: {
          host     : '162.243.32.89',
          adapter  : 'mysql',
          username : 'root',
          password : 'pancakes',
          database : 'test',
        }
      }
    }
  });
```

without deployTo set - it will fail out, I might make a PR for a more helpful and happy error if deployTo isn't set.
